#!/usr/bin/env bash
mkdir -p bin

INDEX="lib/src/index.js"

echo "copy $INDEX to bin"

# ln -sf $(realpath $INDEX) bin/npx-local
(cd bin && ln -sf ../$INDEX npx-local)

chmod +x $INDEX
chmod +x -R bin
